#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEA4L1NjjtOId56y/Rksio2R0NyEr9lUKva8l/S/NYdvgXSznh78KIgu7JVKbDiF/4mvd70zDEx0QRZG7AN2wvsySesyi+9ACXbExi0+d14kXX24dZ7MY52fcOQDnm1UM6GB2tGONZ9mkSy7oNVBUPBQiwTkVkdDBGRtU6zSqk+YGg6uqXS8ornyEWtGNebzVLyrC/AGjT142tc+T4r4o280k33Qy17RjHrBfDa+ljSWgpwOwXYoBtGmDEhxYPlG4g8M18vAPVhj2+lYviMTZFWVtnOe6SmyvXvK6DuPZg8p6zJBdHFA3keVNp9aEdSLa/evUwOx0AqZeBOE+dN9xW16aPMEM5STQIHuzkaWpgHeF5KXCaddhFpj+Bp4bZKm24SKSIZqnm4o36WczYh+aG/01gsNp7VdKgZftmy27OjArr55SGdFysjUPr0I0Sy6oux8/9VEeMzUzTtdHBmdiyIVB04rCJ1mMgplVfzq1dm+Vhb7nUcODERC2YLyXooLRAyy0joJimGvVO75UJpJgxwR2e8dRqvlSQeQ5U1uw/kdN+X/rtU9BBraL7IiDFl+sCh6AW7vTU/3RIG1NGMvjtQUb6zyT97ZDj1HNzY66nOjiJ/ofwW95s8d3CxbVM81VVtwVsmnhIgiGYvMtn/bqja/yFoPhkE4SJqlLmrcfzW7Nc= 
hostname: ROS

rancher:
  network:
    interfaces:
      eth*:
       dhcp: true
    dns:
     nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
