#cloud-config

ssh_authorized_keys:
  - ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAtjh/r9vZpSVD+CxOAS1Bd8I2ozSd+ngcFfefEXHO6faJAqFnWqMVOwP5ciHEBNBoE4GvNjVCQUuMxU8XSOoPq+blLKu+SgOcENCAPGXAm6WBdmiQmgVlY/vo31xWhCAiQjXt1pECzsHxpTuHnJrq9H6CleKtFLnl5AWfBJiJwqJk0JBIL9WTfP63wylgyg0yKdSL9+23gsLXGoTyWZEQHJMubaCPkk3IpDF20gT2mfKiWS6rOeKwSZ8CwY636P7aJBV7Hf+77VEJYJdXDhJS0qnXjubI4Q2Xh8HC1Dt+P9LP/4WrocbsRHL0t6IXriN4IlBxECDY2tcYCt6vO7IwKKwtwsie/QMM+33pz3QZ9bUMUAqDmlRJ7nFdoBwNqn+vvCWBi6/O9MoXfYLX+HUyzB3eimuojvaOepCUm/Di27PvjeJo1edCTapeWixRny1L1+2dRaKFc+q688YifDBOqTnrTixF3MHe4Y8QpVqVurl36JDhjEeyksY+SaYzfPLfRM4/8B4y42rV8SyqM98e0+aOJjR64Mfg5XBqT/vteAUkT9xlBULE1PXktLW+PC0hc9K7rIXsm4edQVyG1E7Z8JO3WayJGTmp9BxmlU1KqQGGK7CL34rvF9GXQCIUuOwgPx/n3moAAt2Tg/YbvnqI2mc2drx7kGgLFu2xaR0W+d0= 
hostname: ROS

rancher:
  network:
    interfaces:
      eth*:
       dhcp: true
    dns:
     nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
