#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAkEdDGdfuxpVmFYMro1Bf7cKgiEsJklK49a7mU35EmgbjUee454sprfxCXp1uNFqkizOiBs7KhM3rGtGXS6Ay4TDMZRwtN/rydw7Rnmm5YwSYF9cfW4XK2p19V5kx/QqT3D/kfTyGAjk5HZGcHbnhhfokBByiuzZ2F1Q9rM/IzMxJl3GG5ve8IYsUsGjbDpt+BE2chKzx9X4Vr9rVNqiW0WkAYhUS8CvHSeRLgOUHc72GmhTISlckRUpjXivNOu2AxOvXDTxmIo4VNWYNZnXyS2R4whoZP2ag7YsF44nsY+fpBiwYFVZYXEcmAsvphdNzZ2JuXB8mqhINGUvguolFMJ+Hq8zadE+/RvKc/OMYTUZIWWtSEvGEfXQdAJUsnSv9vQwO/9zi+A/FYSYNV24bNJyySnInPjn6Nlx3EfqF6jcgF/8qVCuA4RgAop4aDAL8lvgwrbexzNmrycm7PV6u+swhGGkPNmL33A8mTgw+h723OCcZxwhBoF6GeDc8biYzChBRGiG0JIIsno5gwU+9pev4T/wZ3cQ2oTu2VPsIVmM0jKF5Ud39agG4ZvfOdk9eXxKqA1c9TIV3R5IeD1PGVRl4NZWR2+vYIKiK4oqhQ/UGAzis4K7BaxftOiqV88WLfXDSaSSjqIvF8CM96JWM1g4VSSH+R2CdH9MxQNkenYM= 
hostname: ROS

rancher:
  network:
    interfaces:
      eth*:
       dhcp: true
    dns:
     nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
