#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAvudIdx62nMKUxzN9IfJ2EgDeDqqSko83QcgUcbKTo1JhYZnFDjgvB9WWDc5twejvKWBq5KpkYsuBExg8cLQ22WdIc36jWAIG37cK4fRHsD3N1ZOgenYW0JT7LVtdrXoS/h2VrEQHtDUwFtxfRi101xfLXNcWfsoxVunoT8+gaZbJCSO4q9w8pHGH+BqYbRVlCuSCj4ClFfr0fTDN7NcN9S4Zl1Iw4yafnh4W27ec3Dm/CnCosqG4f6eJ488uoobz6H9fIrayeaNdtj6f0sXqxTk9/tEaEK2WloYytW37jXTKSrGkZ9DOtXH7vI9MAyvcdTzNHss2QfqrLqcXru3sapsGFo1r5Gu5gWC75TMFGqCmgD15mMr69lGwx10Nt0kehh/4zDVPIximbeEv25F0hBhmew3LXT+Nz9xc6s0FdD21SqY2yoWD+BN3GzkqlWip4xajSTZ4RB2VZ96hwM4zgb/PB2eh2w5/uABEU4+k7n9vcuDr5wFXu2IOAxhxcyE1ft2zSROKaxyunPvAmUqqzEG85EAoZLF5LUEMFQBBXGP5CJDPCrA6hxaULamN04KDrph9bx/ErZ9S2UVQX5nmpEvwdQR+joBGWclKrhxVNrtP2u6q2ODnJGKf7oX88hddGFSehphZELWEOjvRXa8ym6comugoHhh0wu6cgHSrRm0=
hostname: ROS

rancher:
  network:
    interfaces:
      eth*:
       dhcp: true
    dns:
     nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
